apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mlflow.name }}
  labels:
    {{ .Values.mlflow.labels | toYaml | nindent 4 }}

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path 
