apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.mlflow-catan.name }}
    labels:
       {{ .Values.mlflow-catan.labels | toYaml | nindent 4 }}

spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: local-path 
