apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mlflow.name }}
  labels:
    {{ .Values.mlflow.labels | toYaml | nindent 4 }}

spec:
  ports:
    - port: {{ .Values.mlflow.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{ .Values.mlflow.labels | toYaml | nindent 4 }}

