# Values File for Auto-Catan

# Global Variables
imagePullSecrets: []
replicaCount: 1

mlflow:
  name: mlflow
  labels:
    app: autocatan
    component: mlflow

  image:
    repository: islam25/mlflow
    pullPolicy: IfNotPresent
    tag: "0.0.1"

  service:
    port: 8250

  resources:
    limits:
      cpu: 400m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi

  autoscaling:
    enabled: false

catan-web:
  name: "catan-web"
  labels:
    app: autocatan
    component: "catan-web"

  image:
    repository: islam25/catan_web
    pullPolicy: Always
    tag: "0.0.2"
  
  service:
    port: 8251
  
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  env:
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: chart-redis
          key: redis-password
  
  autoscaling:
    enabled: false

catan-ml:
  name: "catan-ml"
  labels:
    app: autocatan
    component: "catan-ml"

  image:
    repository: islam25/catan_ml
    pullPolicy: Always
    tag: "0.0.1"
  
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 4096Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
  
  env:
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: chart-redis
          key: redis-password
    - name: MINIO_USER
      valueFrom:
        secretKeyRef:
          name: chart-minio
          key: root-user
    - name: MINIO_PASSWORD
      valueFrom:
        secretKeyRef:
          name: chart-minio
          key: root-password

minio:
  persistence:
    enabled: true
    size: 5Gi
  defaultBucket:
    enabled: true
    name: analysis
