[project]
name = "catan-dramatiq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dramatiq[redis]>=1.17.1",
    "minio>=7.2.12",
    "pandas>=2.2.3",
    "pydantic>=2.10.3",
    "pydantic-settings>=2.6.1",
    "torch>=2.5.1",
    "torchaudio>=2.5.1",
    "torchvision>=0.20.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
