apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ index .Values "catan-web" "name" }}
  labels: {{ index .Values "catan-web" "labels" | toYaml | nindent 4 }}
spec:
  {{- if not (index .Values "catan-web" "autoscaling" "enabled") }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{ index .Values "catan-web" "labels" | toYaml | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{ index .Values "catan-web" "labels" | toYaml | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ index .Values "catan-web" "image" "repository" }}:{{ index .Values "catan-web" "image" "tag" | default .Chart.AppVersion }}"
          imagePullPolicy: {{ index .Values "catan-web" "image" "pullPolicy" }}
          ports:
            - name: http
              containerPort: {{ index .Values "catan-web" "service" "port" }}
              protocol: TCP
          livenessProbe:
            httpGet:
                path: /healthz
                port: http
          readinessProbe:
            httpGet:
                path: /healthz
                port: http 
          resources:
            {{- toYaml (index .Values "catan-web" "resources") | nindent 12 }}

