apiVersion: v1
kind: Service
metadata:
  name: {{ index .Values "catan-web" "name" }}
  labels:
    {{ index .Values "catan-web" "labels" | toYaml | nindent 4 }}

spec:
  ports:
    - port: {{ index .Values "catan-web" "service" "port" }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{ index .Values "catan-web" "labels" | toYaml | nindent 4 }}
